### ISSUE TITLE
Don't check for Google Cloud Storage connectivity in stateless mode unless uploading

### ISSUE THREAD

**Issue by ckeeney** [udx/wp-stateless#442] opened 2020-02-16 06:00 UTC
I use `wp-stateless` in `stateless` mode.  Occasionally, the photo sources on my site are all pointing at my own domain name instead of GCS for about a minute or two.  I'm not sure what causes this temporary failure, but I noticed this check for GCS connectivity in the plugin initialization.

In stateless mode, I don't think I care about any GCS connectivity except when uploading media from the wp-admin.  GCS is the only place my images exist, so my own domain name is not a reasonable failover. This should also save on some overhead of unnecessary connections. 

https://github.com/wpCloud/wp-stateless/blob/a93638abe0d2ae5013e0c7f6f7155e8e101c0c33/lib/classes/class-bootstrap.php#L151-L159

**Comment by antonkorotkov** [comment] 2020-02-24 09:17
@ckeeney this connection check here is for informational purposes only. It does not switch modes or whatsoever, but only displays a warning message in admin area. So, despite there is no connection, the images should be loading from GCS. I think your issue was caused by something else.

**Comment by antonkorotkov** [comment] 2020-02-24 12:58
@ckeeney disregard my last message that you maybe noticed. You are right, there may be some unnecessary connection checks. We will investigate what we can do there.

**Comment by antonkorotkov** [comment] 2020-02-24 15:53
The fix will be included in the next release. Thanks.

**Closed as completed by antonkorotkov** 2020-02-24 15:53 UTC
Labels: type/bug
