### ISSUE TITLE
Uploads inserting local URL instead of GCS URL

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#340] opened 2019-01-13 22:22 UTC
https://wordpress.org/support/topic/video-files-404-in-media-library/

We have Stateless mode. All files are uploading to the bucket correctly and getting deleted from our server correctly.

In the Media Library, all files pick up the googleapis link to the bucket correctly, example with an image file:

https://drive.google.com/file/d/1rVgW_zS9LB_OqHhPbGhyedogg0EypzHy/view?usp=sharing

Specifically for videos, the googleapis url does not get loaded and instead the local url is, giving 404 as the video file is in fact not there, example with a video file with the issue below

https://drive.google.com/file/d/1Zi0tOoeRg5Dv75gamKFmCso27hWUZ-sv/view?usp=sharing

All video format files are presenting this issue. Images, documents (pdf, doc) are not.

**Comment by tamara-m** [comment] 2019-01-13 23:26
Expected behavior:
https://drive.google.com/file/d/1rVgW_zS9LB_OqHhPbGhyedogg0EypzHy/view

What is happening when the file is a video file specifically:

https://drive.google.com/file/d/1Zi0tOoeRg5Dv75gamKFmCso27hWUZ-sv/view

Settings:

https://drive.google.com/file/d/1PdFq9J0N2U3IcaAUKJ9ySFFqopf7A91J/view
https://drive.google.com/file/d/1ulEXKieXmclWon84G5jLl8tdr4tUyTsC/view

**Comment by tamara-m** [comment] 2019-01-15 22:50
alimuzzaman I think I have found the issue and solution to our problem. 

How can I share my change so that it gets included in the plugin and we can continue updating it?

What seems to fix the issue is replacing all instances of `$sm_cloud['fileLink']` with `$sm_cloud[0]['fileLink']` in the function `wp_get_attachment_url` from 

/lib/classes/class-bootstrap.php

With the current `$sm_cloud['fileLink']` the first check `!empty( $sm_cloud['fileLink'] )` gives true and returns.

For reference $sm_cloud =
```
Array
(
    [0] => Array
        (
            [id] => 
            [name] => 
            [fileLink] => 
            [storageClass] =>
            [mediaLink] => 
            [selfLink] => 
            [bucket] => 
            [object] => Array
                (
                    [bucket] => 
                    [cacheControl] => 
                    [componentCount] => 
                    [contentDisposition] => 
                    [contentEncoding] => 
                    [contentLanguage] => 
                    [contentType] => 
                    [crc32c] => 
                    [etag] => 
                    [eventBasedHold] => 
                    [generation] =>
                    [id] => 
                    [kind] => 
                    [kmsKeyName] => 
                    [md5Hash] => 
                    [mediaLink] => 
                    [metadata] => Array
                        (
                            [width] => 
                            [height] => 
                            [object-id] => 
                            [source-id] => 
                            [file-hash] => 
                        )
                    [metageneration] => 
                    [name] => 
                    [retentionExpirationTime] => 
                    [selfLink] => 
                    [size] => 
                    [storageClass] => 
                    [temporaryHold] => 
                    [timeCreated] => 
                    [timeDeleted] => 
                    [timeStorageClassUpdated] => 
                    [updated] => 
                )
            [sizes] => Array
                (
                )
            [cacheControl] => public, max-age=30, no-store, must-revalidate
        )
)
```
After adding `[0]` to `$sm_cloud[0]['fileLink']` video files now load the GCS url as shown below for the same attachment that used to fail before.

![image](https://user-images.githubusercontent.com/9288041/51215314-41bad080-18ff-11e9-84fb-54ec44103fad.png)

@alimuzzaman

**Comment by alimuzzaman** [comment] 2019-01-28 16:52
@tamara-m 

I am not sure how did you managed to get a 0 indexed sm_cloud, that isn't normal at all.
`Array
(
    [0] => Array
        (
            [id] => `

Expected is `Array
        (
            [id] => `

`$sm_cloud = get_post_meta( $post_id, 'sm_cloud', 1 );` should have returned single value as the third parameter is passed.
Can you check how the value is saved in database?

Using `$sm_cloud[0]` would create more problem.

**Comment by alimuzzaman** [comment] 2019-01-28 17:01
What do you mean?
> With the current $sm_cloud['fileLink'] the first check !empty( $sm_cloud['fileLink'] ) gives true and returns.

**Comment by tamara-m** [comment] 2019-01-28 19:48
> I am not sure how did you managed to get a 0 indexed sm_cloud, that isn't normal at all.

This is how the plugin saved the data. We are using the plugin out of the box with 0 customization. So it is somehow the plugin core that has managed to get a 0 indexed sm_cloud.

> Can you check how the value is saved in database?

Yes, this is an example:

`a:10:{s:2:"id";s:65:"stateless-peuniverse/2019/01/d0be3728-easter.pdf/1548516830948254";s:4:"name";s:27:"2019/01/d0be3728-easter.pdf";s:8:"fileLink";s:79:"https://storage.googleapis.com/stateless-peuniverse/2019/01/d0be3728-easter.pdf";s:12:"storageClass";s:14:"MULTI_REGIONAL";s:9:"mediaLink";s:141:"https://www.googleapis.com/download/storage/v1/b/stateless-peuniverse/o/2019%2F01%2Fd0be3728-easter.pdf?generation=1548516830948254&alt=media";s:8:"selfLink";s:94:"https://www.googleapis.com/storage/v1/b/stateless-peuniverse/o/2019%2F01%2Fd0be3728-easter.pdf";s:6:"bucket";s:20:"stateless-peuniverse";s:6:"object";a:28:{s:6:"bucket";s:20:"stateless-peuniverse";s:12:"cacheControl";s:45:"public, max-age=30, no-store, must-revalidate";s:14:"componentCount";N;s:18:"contentDisposition";N;s:15:"contentEncoding";N;s:15:"contentLanguage";N;s:11:"contentType";s:15:"application/pdf";s:6:"crc32c";s:8:"lalncA==";s:4:"etag";s:16:"CJ7XjN3ii+ACEAE=";s:14:"eventBasedHold";N;s:10:"generation";s:16:"1548516830948254";s:2:"id";s:65:"stateless-peuniverse/2019/01/d0be3728-easter.pdf/1548516830948254";s:4:"kind";s:14:"storage#object";s:10:"kmsKeyName";N;s:7:"md5Hash";s:24:"hK2JYlPN3UCWwQuHzWkv+g==";s:9:"mediaLink";s:141:"https://www.googleapis.com/download/storage/v1/b/stateless-peuniverse/o/2019%2F01%2Fd0be3728-easter.pdf?generation=1548516830948254&alt=media";s:8:"metadata";a:3:{s:9:"object-id";s:3:"555";s:9:"source-id";s:32:"1a8b784349f514b93a767111404d683c";s:9:"file-hash";s:32:"570b92e32a3810ec0ccee069175342f5";}s:14:"metageneration";s:1:"1";s:4:"name";s:27:"2019/01/d0be3728-easter.pdf";s:23:"retentionExpirationTime";N;s:8:"selfLink";s:94:"https://www.googleapis.com/storage/v1/b/stateless-peuniverse/o/2019%2F01%2Fd0be3728-easter.pdf";s:4:"size";s:5:"87414";s:12:"storageClass";s:14:"MULTI_REGIONAL";s:13:"temporaryHold";N;s:11:"timeCreated";s:24:"2019-01-26T15:33:50.947Z";s:11:"timeDeleted";N;s:23:"timeStorageClassUpdated";s:24:"2019-01-26T15:33:50.947Z";s:7:"updated";s:24:"2019-01-26T15:33:50.947Z";}s:5:"sizes";a:0:{}s:12:"cacheControl";s:45:"public, max-age=30, no-store, must-revalidate";}`

> Using $sm_cloud[0] would create more problem. 

I believe you, just for the record, there have been no problems that we could see yet, and nothing on error logs.

> What do you mean?
> With the current $sm_cloud['fileLink'] the first check !empty( $sm_cloud['fileLink'] ) gives true and returns.

Apologies if that was not clear. I was debugging that function in and confirmed this is what is happening in our site is that: the function doesn't pass thoses checks and returns. As a result of this, the local URLs are fetched instead of the GCS URL.

**Comment by antonkorotkov** [comment] 2019-02-04 14:58
I could not replicate the issue. MP4 file has been successfully uploaded:

![image](https://user-images.githubusercontent.com/2276882/52216024-05471880-289e-11e9-81cf-6c6e5d7fd5ee.png)

**Comment by tamara-m** [comment] 2019-02-04 16:36
The problem was never the upload, that always worked OK. 

The issue was on function `wp_get_attachment_url` in `wp-stateless/lib/classes/class-bootstrap.php`

Updating the plugin to version 2.2.2 **seems to have solved the issue**!

**Comment by antonkorotkov** [comment] 2019-02-05 09:41
> Updating the plugin to version 2.2.2 **seems to have solved the issue**!

Ah, glad to know! Please open a new issue if you still have any questions.

Thanks. Closing.

**Closed as completed by antonkorotkov** 2019-02-05 09:41 UTC
