### ISSUE TITLE
Avatars dont sync

### ISSUE THREAD

**Issue by renduples** [udx/wp-stateless#297] opened 2018-08-30 14:39 UTC
Version 2.1.7 - avatars in media/uploads folder don't sync
Settings: Stateless + File URL replacement + Dynamic Image Support

**Comment by alimuzzaman** [comment] 2018-08-30 15:07
@renduples what kind of avatars are you talking about?

**Comment by renduples** [comment] 2018-09-01 10:14
Local avatars generated by: https://wordpress.org/plugins/simple-local-avatars/
and stored in the /media/uploads folder

**Comment by antonkorotkov** [comment] 2020-02-25 10:34
Hey @renduples 

Sorry for the late response. 

Do you still experience this issue? I'm going to investigate it now but maybe you have something to add. Thanks.

**Comment by antonkorotkov** [comment] 2020-02-25 11:08
I was able to replicate the issue. Investigating a way to fix.

**Comment by renduples** [comment] 2020-02-25 11:10
Awesome thanks

**Comment by antonkorotkov** [comment] 2020-02-25 12:54
Ok, so the issue is that the Simple Local Avatars plugin generates custom image sizes that are not really registered. They are not being synced because the plugin uses a direct image editor which wp-stateless cannot know about.

The only image size that is being synced with GCS is `full`. 

So the only way to fix it for now if to add the following to your theme's `functions.php` or `mu-plugin`:

```php
add_filter('simple_local_avatars_dynamic_resize', '__return_false');
```

But it will make it use the `full` size for the avatars, which is not always good. And unfortunately, it will only be applied to the newly uploaded avatars.

In the meantime, we will work on some more efficient compatibility fix for this plugin.

**Comment by antonkorotkov** [comment] 2020-02-25 13:21
Ok, I just noticed that all required avatars sizes (26, 64, 96) are being synced if `Dynamic Image Support` is enabled. The main issue now if that incorrect URL is being used.

**Comment by antonkorotkov** [comment] 2020-02-26 12:50
The new compatibility option will be added with the next release to support Simple Local Avatars.

![image](https://user-images.githubusercontent.com/2276882/75346421-5827af80-58a7-11ea-88c1-d6ed79733912.png)

**Closed as completed** 2020-02-26 12:50 UTC
Labels: type/compatibility

**Comment by renduples** [comment] 2020-02-26 19:36
Brilliant - thank you
