### ISSUE TITLE
Media files with accent characters do not upload correctly to the bucket

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#272] opened 2018-07-19 12:27 UTC
https://wordpress.org/support/topic/media-files-with-accent-characters-do-not-upload-correctly-to-the-bucket/#post-10507470

>Everything seems fine except for media files that have a special character such as an accented letter in the filename. wp-stateless appears to create a sub-directory named with the special character, and then puts all the wordpress-generated thumbnails inside it. The original media file is placed in the correct directory. But the thumbnails are not. Therefore when the site tries to serve the thumbnails directly from the bucket, it is looking in the wrong place.

>For example, if the media file is uploads/2018/06/željko.png (note the accent on the z character). WordPress generates željko-150×150.png and željko-800×400.png and so on.

>These get uploaded to the bucket as 2018/06/željko.png which is correct and 2018/06/ž/željko-150×150.png and 2018/06/ž/željko-800×400.png which are not correct (note the subdirectory in the path).

>The site tries to access these files without that subdirectory, and therefore can’t find them.

**Comment by alimuzzaman** [comment] 2018-07-19 19:27
@Mashenka can you check please.
It's working fine for me.

**Comment by Mashenka** [comment] 2018-07-19 19:51
checking, right now can't replicate

**Comment by ewsopp** [comment] 2018-07-19 23:04
It might be helpful to have the actual file for testing.

**Comment by russwiltshire** [comment] 2018-07-20 09:23
Hi. I'm the original poster in the support forum. Have you discovered a bug, fixed it, and you want the original file to test if your fix works? Or are you saying you can't replicate the problem? We transferred over 5000 images and every one of them with an accent character ended up being treated in the same way: original files were uploaded correctly, but the auto-generated thumbnails were not. I could send you some of the PNG files to test it with but please be aware that it was only the auto-generated thumbnails that were being uploaded incorrectly. Let me know if you want some test files.

I note your request to try it without third party plugins. I have not tried this. I will do this later today and report back.

**Comment by alimuzzaman** [comment] 2018-07-20 11:04
@russwiltshire 
We wasn't able to replicate the problem.
If you send some of your file it would be helpful.
What do you mean by *auto-generated thumbnails*, regular wp thumbnail or stateless generate when sync?

**Comment by russwiltshire** [comment] 2018-07-20 11:22
I am referring to the wordpress thumbnails. As I understand it, wordpress standard behaviour is that when you add an image to the media library it will automatically create some additional images of different sizes. So the thing is, even if I send you some files to test with, they all might work correctly. But to repeat the steps I'm taking, you would need to upload one image to the wordpress media library, let wordpress create the thumbnails automatically, then activate wp-stateless and see what it does to all the files (the original one and the ones that wordpress generates).

**Comment by russwiltshire** [comment] 2018-07-20 11:32
![screen shot 2018-07-20 at 13 29 54](https://user-images.githubusercontent.com/25862572/43000309-3fe34366-8c21-11e8-899c-fa93c9694967.png)
![screen shot 2018-07-20 at 13 30 42](https://user-images.githubusercontent.com/25862572/43000310-400709fe-8c21-11e8-9a07-c962174fe6d3.png)
![screen shot 2018-07-20 at 13 30 58](https://user-images.githubusercontent.com/25862572/43000312-40284150-8c21-11e8-830e-af454db6f78f.png)
![zeljko-1](https://user-images.githubusercontent.com/25862572/43000326-4a2f78f8-8c21-11e8-8660-5bae1977a28c.png)

**Comment by russwiltshire** [comment] 2018-07-20 11:40
Previous comment has screenshots showing the file listing from the server, and what the bucket looks like after wp-stateless does it's magic. Also the original file that was uploaded to wordpress media library.

**Comment by russwiltshire** [comment] 2018-07-20 11:43
Hmm... sorry, tried to upload the image but it doesn't seem to have worked. What's the best way to get the original image file to you?

**Comment by alimuzzaman** [comment] 2018-07-20 11:44
Google drive.

**Comment by russwiltshire** [comment] 2018-07-20 13:09
https://drive.google.com/open?id=1bNwImOTs1CjFBLqdCMZZQMlFZwVVy8n_

**Comment by russwiltshire** [comment] 2018-07-20 14:01
Hi. So I tested this on a new site. I can't replicate the issue. Which is good news for you but not me :)

New WordPress install. A couple of other plugins installed but deactivated. Installed wp-stateless. Set to CDN mode. Synced existing media which doesn't contain accented chars. Everything went to the bucket fine. Added media files with filenames starting with ž. Each file was saved to the uploads directory with a prefix of about 10 random characters. Those files were transferred to the bucket fine. Deactivated wp-stateless. Uploaded another file starting with ž. It was added to the uploads directory without a prefix. Activated wp-stateless again. Did another sync. That file (and it's thumbnails) transferred to the bucket fine as well.

As an aside, could you confirm that when wp-stateless is active, it adds a random prefix to media filenames as they are added to the media library?

Getting back to the cause of the original problem then... you mentioned testing this with all third party plugins disabled, which I've now done as described above. And the problem is not present. So, would this suggest it's a plugin incompatibility? It seems unlikely because we're talking about thumbnails that are already on the server, inside the uploads folder. They've already been created. Then, when wp-stateless processes them, they end up in an odd subdirectory in the bucket. I can't see that any other plugin is involved during the process of wp-stateless picking files out of the uploads directory and sending them to the bucket.

The differences between this new site and the one where I saw the problem are: different server, but built from the same image and configured the same way; different theme in WordPress; no active plugins on the new site but lots of active plugins on the old site.

I imagine what you're going to say now is that I should systematically switch off plugins on the problem site until I find which one is screwing up the transfer to the bucket. But any chance you could help shortcut this by confirming if it's even possible for any other plugin to be involved during a wp-stateless sync process?

Thanks.

**Comment by russwiltshire** [comment] 2018-07-20 14:04
I answered my own question about the prefix - it's your cache busting feature.

But some advice on plugin interactions during a wp-stateless sync process would still be appreciated.

**Comment by alimuzzaman** [comment] 2018-07-20 15:06
The problem is most likely in server configuration.
Here is the php bug https://bugs.php.net/bug.php?id=62119
Will try to find a solution.

**Comment by russwiltshire** [comment] 2018-07-20 16:03
LANG variable is 'C' on both servers if that helps.

**Comment by alimuzzaman** [comment] 2018-07-20 16:30
@russwiltshire Can you test this version [2.1.6-RC4](https://github.com/wpCloud/wp-stateless/releases/tag/2.1.6-RC4) ?

**Comment by russwiltshire** [comment] 2018-07-20 17:01
ok, will do. Over the next couple of days. Thank you.

**Comment by russwiltshire** [comment] 2018-07-22 12:50
Looks like this version is working. On the original site where the problem was, I chose "disabled" mode in stateless settings, I deactivated the old wp-stateless plugin, deleted it, unzipped 2.1.6-RC4 in the plugins folder, activated it, settings had been retained so it was still in "disabled" mode. I then created a new bucket, changed the bucket name in the settings, switched to "backup" mode, and then set a sync running. I let it copy almost 2000 images to the bucket. The example file I had trouble with before which begins with a ž character was uploaded fine (both the original and all the thumbnails). Other files that contain accent characters somewhere within the filename also uploaded fine. I also uploaded new files to the media library which contained and/or began with accent characters and they transferred to the bucket fine.

I'm satisfied this is working now. Thanks for all your help.

**Closed as completed** 2018-07-24 19:21 UTC
