### ISSUE TITLE
Divi Child Theme

### ISSUE THREAD

**Issue by danielsalare** [udx/wp-stateless#351] opened 2019-02-02 01:40 UTC
We have a Divi child theme but the Divi option is not enabled. What does this compability do? 
Everything seems to be working fine, but the only issue is that IDP (product detail) is not using the google storage images. 

<img width="696" alt="screen shot 2019-02-01 at 7 36 17 pm" src="https://user-images.githubusercontent.com/364171/52157968-2c60d880-2659-11e9-86fe-a3ece2bb3517.png">
<img width="142" alt="screen shot 2019-02-01 at 7 36 41 pm" src="https://user-images.githubusercontent.com/364171/52157969-2e2a9c00-2659-11e9-80cb-23cd207cbce4.png">

**Comment by alimuzzaman** [comment] 2019-02-14 13:15
@danielsalare 
The compatibility is for `Divi Builder Export`. You can check issue #224 for details.
For now you can use constant `WP_STATELESS_COMPATIBILITY_DIVI` to enable it.

Can you please clarify IDP (product detail)?

**Comment by danielsalare** [comment] 2019-02-14 15:51
The IDP issue is detailed on issue #353 

Regards

**Comment by antonkorotkov** [comment] 2019-02-26 15:16
@alimuzzaman are we good to close this issue? For me it looks like a duplicate of #353

**Comment by alimuzzaman** [comment] 2019-02-26 15:20
@antonKorotkov
Yes you can close it after reviewing the commit.

**Closed as completed** 2019-02-26 15:22 UTC
Labels: type/bug
