### ISSUE TITLE
html tags incorrectly applied in notice

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#680] opened 2023-10-05 19:34 UTC
Also remove the comma after `Please` in the second sentence. 

<img width="1348" alt="image" src="https://github.com/udx/wp-stateless/assets/5578537/50367fed-af69-4536-b061-06c10dda188d">

<img width="1348" alt="image" src="https://github.com/udx/wp-stateless/assets/5578537/deb88621-ceb1-4db4-bf48-63f72130b2f9">

**Comment by balexey88** [comment] 2023-10-09 13:11
I was not able to reproduce exactly the same issues. Tried WP version 6.2 as on the screenshots by also no luck.
Possibly there is some issue with the theme or plugin?

In general I looked through the source code for the possible issues, but it's hard to reproduce all the possible cases. I'll keep an eye on this in the future and fix if I notice something, 

Made the following changes:
- Fixed the message when plugin fails to load
<img src="https://github.com/udx/wp-stateless/assets/12548662/64474ede-f989-4263-b111-07e43f64bea9" height="150"/>

- Fixed the message regarding PHP requirements (it was checking for PHP 5.5)
<img src="https://github.com/udx/wp-stateless/assets/12548662/32cc4d54-10a9-4ccf-b25f-e5e6901f96aa" height="150"/>

- Removed comma and `<b>` tags in the heading
> Also remove the comma after Please in the second sentence. 

This is how it looks on my testing env:
![image](https://github.com/udx/wp-stateless/assets/12548662/45218f13-7f48-4950-a05d-fdb06487cb90)

![image](https://github.com/udx/wp-stateless/assets/12548662/70b2ac14-f058-4a08-a5d3-174abcb7dfba)

**Comment by planv** [comment] 2023-10-17 12:18
Fix was released with version `3.2.5`
Closing the ticket.

**Closed as completed by planv** 2023-10-17 12:18 UTC
Labels: type/bug
