### ISSUE TITLE
Improve error notice

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#244] opened 2018-05-22 15:47 UTC
In general, there are no non-images files in the media library, but notice is not clear

Notice may also mention information, that there is no any non-images file in your library
![image](https://user-images.githubusercontent.com/5111163/40373910-99e52b4a-5df0-11e8-9730-cec858b1b54b.png)

**Comment by Mashenka** [comment] 2018-05-25 11:22
@alimuzzaman still see an old warning

I'm testing from this branch
https://github.com/wpCloud/wp-stateless/tree/develop-alim

![image](https://user-images.githubusercontent.com/5111163/40542072-2ebe476e-6027-11e8-86b1-11a3c941b626.png)

**Comment by ewsopp** [comment] 2018-05-25 12:54
This is an enhancement, not a bug fix. We should wait to include this in 2.1.6 or some other future release.

@Mashenka We are reviewing a release candidate right now. This means we only prioritize bug fixes for 2.1.5. If you want a new feature or enhancement, create an issue and do not assign it to 2.1.5 milestone.

**Comment by Mashenka** [comment] 2018-05-28 08:39
@ewsopp ok, moved to next milestone

**Comment by Mashenka** [comment] 2018-06-18 11:49
Here is one more example where error notice is not clear - https://wordpress.org/support/topic/status-error-appeared-2/#post-10400247

**Comment by Mashenka** [comment] 2018-06-19 20:59
@alimuzzaman 

Unable to get non-library files - > Non-libraries files are not found
and when request failed, can we mention a reason or possible reason?

this one looks good
![image](https://user-images.githubusercontent.com/5111163/41624284-dc15098e-741d-11e8-8e8a-cd98ec343300.png)

**Comment by alimuzzaman** [comment] 2018-06-20 21:39
@Mashenka How does this look?

![image](https://user-images.githubusercontent.com/6744156/41687604-2c2364c4-750a-11e8-9f82-418c30f2c253.png)

**Comment by ewsopp** [comment] 2018-06-20 21:56
All notices should be using our new notice design. related issue at https://github.com/wpCloud/wp-stateless/issues/219

**Comment by alimuzzaman** [comment] 2018-06-20 22:47
This would shown in very rare case:
Normal:
![image](https://user-images.githubusercontent.com/6744156/41688421-e8ddc76e-750d-11e8-9514-ebed6489a55b.png)

After expanded:
![image](https://user-images.githubusercontent.com/6744156/41688426-ec74c29c-750d-11e8-9fe4-638541b21f81.png)

**Comment by Mashenka** [comment] 2018-06-21 13:27
Looks good now.

**Comment by ewsopp** [comment] 2018-06-21 13:35
No this looks terrible.

**Comment by ewsopp** [comment] 2018-07-19 22:51
@alimuzzaman is this an error notice that we generate? Or are we restyling an error notice generated by WordPress?

**Comment by alimuzzaman** [comment] 2018-07-20 11:37
@ewsopp Yes it's our notice. But we are showing what wp-ajax is sending in response other than success. 
In that case of ajax response return wp db error and we just displayed in our notice box.

**Comment by ewsopp** [comment] 2018-07-20 13:46
Alright, lets just leave it as is for now.

**Closed as completed by ewsopp** 2018-07-20 13:46 UTC
