### ISSUE TITLE
Elementor CSS files path

### ISSUE THREAD

**Issue by luckysistemi** [udx/wp-stateless#588] opened 2020-12-06 11:46 UTC
I see that elementor files are uploaded in “elementor” folder in the root of the bucket.

This cause conflicts when using the same bucket for multi sites

Css files are also not loaded in frontend pages

**Comment by antonkorotkov** [comment] 2020-12-22 09:03
Hey,

we were able to reproduce this and plan on having a fix in 3.1.1.

**Comment by luckysistemi** [comment] 2020-12-22 10:14
Thank you.
I propose this solution that seems to fix the problem.

file lib/classes/compatibility/elementor.php

add this in module_init function:
`$root_dir = ud_get_stateless_media()->get('sm.root_dir');
$this->base_path = strtok($root_dir, '%');`

modify this line in sync_rewrite_url:
`do_action('sm:sync::syncFile', $this->base_path.$name, $absolutePath);`


modify delete_elementor_files:
`do_action('sm:sync::deleteFiles', $this->base_path.'elementor/');`

modify one line in delete_css_files:
`do_action('sm:sync::deleteFile', $this->base_path.$name);`


modify one line in delete_global_css:
`do_action('sm:sync::deleteFile', $this->base_path.$name);`

this fix the problem and allow to work in multisite setup.
I assume that the first part of the bucket path is common to all the sites.
The best could be to add a new option to specify this path

**Comment by antonkorotkov** [comment] 2020-12-22 10:23
I have already looked over this on WP.org forum but it is going to be a bit different because your solutions tried to apply the `Folder` structure setting to files created by compatibilities. And it goes differently from what it initially does.

All compatibility files on multisite installation will be uploaded to the default folder that is `sites/%blog_id%/...` disregarding what is configured in `Folder` setting.

So on multisite, instead of uploading everything to the root of the bucket it will do replicate the default multisite structure. 

I understand your solution but it is not going to work if you decide to sync back from GCS, let's say in `CDN` mode, to keep your files locally AND remotely.

**Comment by planv** [comment] 2023-06-22 15:08
It was released with https://github.com/udx/wp-stateless/pull/592
Closing the ticket

**Closed as completed by planv** 2023-06-22 15:08 UTC
