### ISSUE TITLE
buddypress avatar are not upload to the correct place

### ISSUE THREAD

**Issue by gfirem** [udx/wp-stateless#526] opened 2020-08-24 15:33 UTC
Hi, I'm using the stateless configuration and the avatars not get sync to the correct place when the user changes it. 

GCP
![image](https://user-images.githubusercontent.com/11023116/91064617-dae6b880-e605-11ea-9236-689077529856.png)
Local
![image](https://user-images.githubusercontent.com/11023116/91064679-f5209680-e605-11ea-8fbc-6942109f38da.png)

The files in the root of the folder belong to one user 31. Any idea why this behavior?

**Comment by planv** [comment] 2020-10-07 08:50
Hello @gfirem 

I can't reproduce this issue. It works for me
![image](https://user-images.githubusercontent.com/5268508/95308802-01e60a80-0893-11eb-956c-d1053b56eb81.png)

Please provide more details - plugins version, why user `31` has 5 files for avatar, do you have these 5 files on your local folder `31`, etc.

Thanks.

**Comment by ewsopp** [comment] 2020-10-16 23:11
Closing. If issue persists, please re-open with more details.

**Closed as completed by ewsopp** 2020-10-16 23:11 UTC
Labels: type/compatibility
