### ISSUE TITLE
GCS URL isn't being set until image optimized

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#362] opened 2019-03-09 20:23 UTC
https://wordpress.org/support/topic/new-media-items-not-updating-with-correct-url/

Affected compatibility: Imagify and Smush.

The sync is being done after Imagify complete the optimization.  So we don't get GCS URL until the optimization is completed.

We previously solved it by syncing the full size image first then sync all sizes again when optimization completes.
But the issue in 2.2.4 arrived when we changed (in issue #359) how Imagify prevent the sync on image upload.

Now we have to make sure that Optimization plugins don't prevent when we try to upload full size image first.

We had to do this in this way  for performance measure. Unless we would have to sync twice once after upload and again when image optimized.

**Comment by alimuzzaman** [comment] 2019-03-16 14:32
It also prevents the manual sync.

**Comment by alimuzzaman** [comment] 2019-03-16 15:01
@ewsopp 
Now GCS url will be used but preview won't be available until the image optimization is done.

So we have two option:

1. We don't skip the sync on upload. We will have to sync twice, once on upload, another on when optimization done.
2. We add a constant to choose whether to upload twice or performance. We can try to add a loading animation on the edit post page until the image is optimized and fully synced. 

@antonkorotkov do you have any idea?

**Comment by antonkorotkov** [comment] 2019-03-18 09:31
I think this issue should be moved to the next milestone. @alimuzzaman Can you make sure your commits to this issue do not break anything or just revert them so that we can do a release safely. We need to do it today/tomorrow.

**Comment by alimuzzaman** [comment] 2019-03-20 14:09
@antonkorotkov 
No it will not break anything.

**Comment by antonkorotkov** [comment] 2019-03-20 14:10
Ok, thanks

**Comment by alimuzzaman** [comment] 2019-03-31 22:03
@antonkorotkov Need help.

**Comment by antonkorotkov** [comment] 2019-04-01 07:41
> Need help.

what exactly?

**Comment by alimuzzaman** [comment] 2019-04-01 07:56
Syncing in Stateless mode with image optimizer is a mess.

The normal process for sync in Stateless mode with image optimizer:

1. Image get synced and deleted from the server.
2. The image gets downloaded from GCS to the server for optimization.
3. Again optimized image gets synced and deleted from the server.

With the use of `wp_stateless_skip_add_media` filter and sync full image first feature, we can skip step 1 but that creates a new problem. Optimizer takes some time to optimize the image. So when we insert a new image in edit post page image gets broken, because no other image size is available on GCS.

In the last commit, I tried to disable SKIP ADD MEDIA when uploading via edit post page. But that doesn't help at all.

**Comment by antonkorotkov** [comment] 2019-04-01 07:58
Does this problem exist in Stateless mode only?

**Comment by alimuzzaman** [comment] 2019-04-01 08:03
Didn't test in other modes, should be there also.

>  and sync full image first feature

It ensures that GCS URL gets inserted in the post.

**Comment by antonkorotkov** [comment] 2019-04-01 08:11
I don't understand this part: `So when we insert a new image in edit post page image gets broken, because no other image size is available on GCS.`

Why we insert a new image?

**Comment by alimuzzaman** [comment] 2019-04-01 08:12
Sorry not we the user.

**Comment by antonkorotkov** [comment] 2019-04-01 08:17
Ok, what can we really do with this?

**Comment by alimuzzaman** [comment] 2019-04-01 08:23
I think if you take a look you might have some idea.

**Comment by antonkorotkov** [comment] 2019-04-01 08:30
Ok, will try to look into it this week. Please, give me the instructions on how to setup optimization plugin and steps to reproduce the issue.

**Comment by alimuzzaman** [comment] 2019-04-03 14:11
Check with both released and develop-alim branch.
1. Stateless Mode.
2. Enable Smush plugin.
3. Upload a new image from new/edit post page.
4. Change Image Size from right side metabox.

![image](https://user-images.githubusercontent.com/6744156/55485500-61cf7580-564c-11e9-8e21-4dcbdd3fd5d3.png)

**Comment by antonkorotkov** [comment] 2019-04-04 14:23
I don't have enough time to look into it. Moving to the next milestone.

**Comment by alimuzzaman** [comment] 2019-05-03 16:40
I have disabled the lazy sync (skip_add_media).

So the workflow should be now:

1. On upload sync to gcs.
2. Before optimization download from GCS to server if image not exists.
3. Sync again, with backup image.

So there won't be any problem because all image sizes will sync on upload and after optimization (twice).
Previously we skipped the step 1 for performance, what caused some problem.

**Closed as completed** 2019-05-06 11:43 UTC
Labels: type/bug, type/compatibility
