### ISSUE TITLE
getting error writable Unable to create directory  Is its parent directory writable by the server?

### ISSUE THREAD

**Issue by mxo2** [udx/wp-stateless#264] opened 2018-06-27 06:43 UTC
Hi,

We have deploy Wp multisite on the App engine and configure plugin . 

We are getting the following error when we upload media files .. is anybody and assist.

Unable to create directory MY_BUCKET/2018/06. Is its parent directory writable by the server?

We have gcloud VM and there the plugin works perfectly.

Thx

**Comment by alimuzzaman** [comment] 2018-06-27 14:11
It doesn't look like the problem is in our plugin.
Try to isolate the problem by enable disable plugins/themes.
Which server you are using now?

**Comment by mxo2** [comment] 2018-06-27 14:46
Hi,

We are using google App engine multiple site wordpress.

We have disabled plugins but there is not effect ..

Is Themes creates problem ? we have The7 theme is its any setting for this..

Thank you for your reply and want quick reply...

**Comment by alimuzzaman** [comment] 2018-06-27 14:48
It's seems more like config or server side problem.

**Comment by mxo2** [comment] 2018-06-27 14:51
what config we need for this because we cant change file permission on the app engine instances..we have google bucket and we can have all rights on that but the path is changed and dont know where this config to change it.

**Comment by antonkorotkov** [comment] 2018-06-27 15:32
@alimuzzaman Any thoughts regarding what is `MY_BUCKET` is?

**Comment by alimuzzaman** [comment] 2018-06-27 15:33
@antonkorotkov I have no idea.
@mxo2 Do you have any idea?

**Comment by mxo2** [comment] 2018-06-27 16:33
Bucket is google cloud storage ..Where we can upload static content

---- On Wed, 27 Jun 2018 08:33:49 -0700 notifications@github.com wrote ----

@antonkorotkov I have no idea.
@mxo2 Do you have any idea?

**Comment by mxo2** [comment] 2018-06-28 04:29
Now Other directory error after removing some plugin
Unable to create directory wp-content/blogs.dir/7/files/sites/7/2018/06. Is its parent directory writable by the server?

**Comment by antonkorotkov** [comment] 2018-06-28 07:01
@mxo2 You need to make that directory writable. Set 775 permissions to it. `sudo chmod 775 'your directory'`

**Comment by mxo2** [comment] 2018-06-28 07:11
We cant make writeable on google app engine so we are using google bucket for media files.

**Comment by antonkorotkov** [comment] 2018-06-28 07:20
Unfortunately, it is required to upload files to your server first. Then plugin sends files to GCS. It cannot send files directly to GCS without doing standard actions that required by WordPress.

**Comment by mxo2** [comment] 2018-06-28 07:31
Is any plugin also cant help ??

Than app engine is not for wordpress users ?

**Comment by alimuzzaman** [comment] 2018-06-28 08:10
@mxo2 You can try official google plugin.

**Comment by mxo2** [comment] 2018-06-28 12:01
how I can make upload folder on remote location ?? if I can manage it I can upload files at bucket

**Comment by ewsopp** [comment] 2018-06-28 12:47
These issues are unrelated to WP-Stateless. Closing issue.

**Closed as completed by ewsopp** 2018-06-28 12:47 UTC

**Comment by mxo2** [comment] 2018-06-28 12:49
@ewsopp we are not able to upload media files through the addond...Bcoz its using /wp-content/upload folder once to upload on remote location..can we change to any other remote location or google bucket for the same.

**Comment by ewsopp** [comment] 2018-06-28 12:53
> can we change to any other remote location or google bucket for the same

At this time you cannot.

**Comment by engvie** [comment] 2024-03-22 10:34
I had the problem "Unable to create directory...". I found that the problem was with my docker image when I realised it worked with a "default" wordpress image.

The problem I had was that this option was "Off" in the php.ini settings. This must be on.
`allow_url_fopen`

I hope this helps someone
