### ISSUE TITLE
adding a option to select CDN URL

### ISSUE THREAD

**Issue by ashutoshpw** [udx/wp-stateless#88] opened 2017-04-30 22:54 UTC
As of now it is using default Google Storage bucket CDN URL starting with **https://storage.googleapis.com/<bucket_name>**

There should be an option whether the user want to use 
1. https://storage.googleapis.com/<bucket_name> OR
2. http://bucket-name/path/

**Comment by alimuzzaman** [comment] 2017-05-02 14:37
@ashutoshpw 
While we are working on it here a quick fix.
Here are some useful links for how to setup.
http://www.connecto.io/blog/creating-a-cdn-on-your-custom-domain-using-google-cloud-storage/
https://cloud.google.com/storage/docs/hosting-static-website

Drop this code in your themes function.php or where you want.

```
add_action('init', function(){
  if( function_exists('ud_get_stateless_media') && ud_get_stateless_media()->get( 'sm.mode' ) === 'cdn' ) {
    $search_url   = 'https://storage.googleapis.com/' . ud_get_stateless_media()->get( 'sm.bucket' );
    $replace_url  = 'http://' . ud_get_stateless_media()->get( 'sm.bucket' );

    if ( ud_get_stateless_media()->get( 'sm.body_rewrite' ) == 'true' ) {
      add_filter( 'the_content', function($bucketLink){
        return str_replace($search_url, $replace_url, $bucketLink);
      }, 20 );
    }
    add_filter('wp_stateless_bucket_link', function($bucketLink){
      return str_replace($search_url, $replace_url, $bucketLink);
    });
    
    add_filter( 'wp_get_attachment_url', function( $url = '', $post_id = '' ){
      return str_replace('https:http://', 'http://', $url);
    }, 22, 2 );
  }
});
```

**Comment by ashutoshpw** [comment] 2017-05-03 03:40
Well, I actually changed the URL by changing code in my WP stateless code.

**Comment by ewsopp** [comment] 2017-06-30 20:15
@ashutoshpw we are going to include this in the next release. Hopefully, it will ship by next week. Thanks!

**Comment by ewsopp** [comment] 2017-07-13 14:15
duplicate of https://github.com/wpCloud/wp-stateless/issues/98. closing.

**Closed as completed by ewsopp** 2017-07-13 14:15 UTC
